name: CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ${{ secrets.REGISTRY_HOST }}
  IMAGE_NAME: ${{ github.repository }}
  HUGO_VERSION: 0.124.1

jobs:
  build:
    if: github.event.head_commit.author.email == 'ci@git.inpt.fr'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        run: |
          git init .
          git lfs install
          git remote add origin https://japan7:${{ secrets.GITLAB_PAT }}@git.inpt.fr/japan7/website.git
          git fetch origin ${{ github.event.head_commit.message }}
          git checkout FETCH_HEAD
          git submodule init
          git config submodule.aij.url https://pat:${{ secrets.AIJ_CI_PAT }}@git.inpt.fr/japan7/aij.git
          git submodule update
      - run: |
          wget -O /tmp/hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v${{ env.HUGO_VERSION }}/hugo_${{ env.HUGO_VERSION }}_linux-amd64.tar.gz
          tar xvf /tmp/hugo.tar.gz -C /usr/local/bin/
      - run: hugo --minify
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: type=raw,value=latest
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          cache-to: type=inline
    outputs:
      digest: ${{ steps.build-and-push.outputs.digest }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout nanak8s
        uses: actions/checkout@v5
        with:
          repository: Japan7/nanak8s
          token: ${{ secrets.NANAK8S_PAT }}
      - name: Set deploy environment
        id: deploy_env
        run: echo "::set-output name=tag::sha-${GITHUB_SHA::7}"
      - name: Update nanak8s
        env:
          DIGEST: ${{ needs.build.outputs.digest }}
        run: |
          yq e -i "(.environments.default.values[] | select(has(\"digest\"))).digest = \"$DIGEST\"" apps/website/environments.yaml
          git add apps/website/environments.yaml
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -m "[CI] Update website to ${{ steps.deploy_env.outputs.tag }}" -m "https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA"
          git push
